[workspace]
resolver = "2"
members = [
    "crates/cargo-tops",
    "examples/parser-codec",
    "examples/no-std-embedded",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.1"
rust-version = "1.85"
repository = "https://github.com/Hedronite/rust-tops"

[workspace.lints.rust]
unsafe_code = "forbid"
